In [4]:
import numpy as np

In [1]:
s = 5
s

5

In [5]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [6]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

In [13]:
m.shape

(3, 3)

In [14]:
v.shape

(3,)

In [15]:
v.reshape(1, 3)

array([[1, 2, 3]])

In [18]:
v.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [19]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [20]:
s_array.shape

()