In [1]:
import numpy as np

In [2]:
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m2 = np.array([[7, 8, 9], [10, 11, 12]])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
t = np.array([m1, m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
t.shape

(2, 2, 3)

In [11]:
t_manual = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
t_manual

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])