In [4]:
import numpy as np

In [5]:
10 -  6

4

In [7]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
m3 = np.array([[7, 8], [10, 11]])

In [8]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [9]:
v1 = np.array([1, 2, 3, 4, 5, 6])

In [10]:
v3 = np.array([1, 2, 3])

In [11]:
v1 + v3

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [12]:
m1 + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
v1 + 1

array([2, 3, 4, 5, 6, 7])

In [14]:
m1 + np.array([1])

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
v1 + np.array([1])

array([2, 3, 4, 5, 6, 7])