In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
B = np.array([[1, 2], [4, 5]])
B

array([[1, 2],
       [4, 5]])

In [6]:
B.T

array([[1, 4],
       [2, 5]])

In [7]:
a = np.array([1])
a

array([1])

In [8]:
a.T

array([1])

In [9]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [10]:
x.T

array([1, 2, 3])

In [11]:
x.shape

(3,)

In [15]:
x_reshaped = x.reshape(1, 3)
x_reshaped

array([[1, 2, 3]])

In [16]:
x_reshaped.T

array([[1],
       [2],
       [3]])