In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [5]:
np.dot(x, y)

32

In [6]:
u = np.array([0, 2, 5, 8])
v = np.array([20, 3, 4, -1])

In [7]:
np.dot(u, v)

18

In [8]:
np.dot(5, 6)

30

In [9]:
np.dot(10, -2)

-20

In [10]:
5 * x

array([ 5, 10, 15])

## Matriz * Matriz

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [4, 5], [7, 8]])

In [16]:
np.dot(A, B)

array([[30, 36],
       [66, 81]])

In [19]:
m_4_x_5 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
m_4_x_5

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [20]:
m_5_x_2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
m_5_x_2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])